spring:
  datasource:
    url: ${URL:jdbc:mysql://localhost:3306/users}
    username: ${USER_NAME:root}
    password: ${USER_PASSWORD:1234}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop